<% project_name = 'street_fighter_ii' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= street_fighter_ii %>_development

test:
  <<: *default
  database: <%= street_fighter_ii %>_test
